/**
 * OpenTimelineIO (.otio) 互換層
 *
 * 10年運用のための業界標準互換性。
 * Pixar 開発、DaVinci Resolve / Premiere / FCP / Avid 採用。
 *
 * 仕様: https://opentimeline.io
 * スキーマ: SchemaDef-1
 *
 * インポート/エクスポートで他 NLE と往復編集可能。
 */

// === OTIO スキーマ型定義 ===

interface OTIORationalTime {
  OTIO_SCHEMA: 'RationalTime.1';
  rate: number;
  value: number;
}

interface OTIOTimeRange {
  OTIO_SCHEMA: 'TimeRange.1';
  duration: OTIORationalTime;
  start_time: OTIORationalTime;
}

interface OTIOMediaReference {
  OTIO_SCHEMA: 'ExternalReference.1' | 'MissingReference.1' | 'GeneratorReference.1';
  available_range?: OTIOTimeRange;
  metadata?: Record<string, unknown>;
  name?: string;
  target_url?: string;
}

interface OTIOEffect {
  OTIO_SCHEMA: 'Effect.1' | 'TimeEffect.1';
  effect_name: string;
  metadata?: Record<string, unknown>;
  name?: string;
}

/**
 * OTIO LinearTimeWarp.1 — constant-speed retiming effect.
 * `time_scalar` > 1 = slower playback (more source frames per output frame).
 * `time_scalar` < 1 = faster playback.
 */
interface OTIOLinearTimeWarp {
  OTIO_SCHEMA: 'LinearTimeWarp.1';
  effect_name: string;
  /** Speed multiplier: 1.0 = normal, 2.0 = half speed (plays at 50%), 0.5 = double speed (200%). */
  time_scalar: number;
  metadata?: Record<string, unknown>;
  name?: string;
}

type OTIOAnyEffect = OTIOEffect | OTIOLinearTimeWarp;

interface OTIOMarker {
  OTIO_SCHEMA: 'Marker.1' | 'Marker.2';
  color: 'PINK' | 'RED' | 'ORANGE' | 'YELLOW' | 'GREEN' | 'CYAN' | 'BLUE' | 'PURPLE' | 'MAGENTA' | 'BLACK' | 'WHITE';
  marked_range: OTIOTimeRange;
  metadata?: Record<string, unknown>;
  name?: string;
  comment?: string;
}

interface OTIOClip {
  OTIO_SCHEMA: 'Clip.1' | 'Clip.2';
  effects: OTIOAnyEffect[];
  markers: OTIOMarker[];
  media_reference: OTIOMediaReference;
  metadata?: Record<string, unknown>;
  name: string;
  source_range: OTIOTimeRange;
  enabled?: boolean;
}

interface OTIOGap {
  OTIO_SCHEMA: 'Gap.1';
  effects: OTIOEffect[];
  markers: OTIOMarker[];
  metadata?: Record<string, unknown>;
  name?: string;
  source_range: OTIOTimeRange;
}

interface OTIOTransition {
  OTIO_SCHEMA: 'Transition.1';
  metadata?: Record<string, unknown>;
  name?: string;
  transition_type: 'SMPTE_Dissolve' | string;
  parameters?: Record<string, unknown>;
  in_offset: OTIORationalTime;
  out_offset: OTIORationalTime;
}

type OTIOTrackChild = OTIOClip | OTIOGap | OTIOTransition;

interface OTIOTrack {
  OTIO_SCHEMA: 'Track.1';
  children: OTIOTrackChild[];
  effects: OTIOEffect[];
  kind: 'Video' | 'Audio';
  markers: OTIOMarker[];
  metadata?: Record<string, unknown>;
  name?: string;
  source_range?: OTIOTimeRange | null;
}

interface OTIOStack {
  OTIO_SCHEMA: 'Stack.1';
  children: OTIOTrack[];
  effects: OTIOEffect[];
  markers: OTIOMarker[];
  metadata?: Record<string, unknown>;
  name?: string;
  source_range?: OTIOTimeRange | null;
}

interface OTIOTimeline {
  OTIO_SCHEMA: 'Timeline.1';
  global_start_time?: OTIORationalTime | null;
  metadata?: Record<string, unknown>;
  name: string;
  tracks: OTIOStack;
}

// === 内部型 (Artone 側 — 既存実装と整合) ===

export interface ArtoneTimeline {
  name: string;
  fps: number;
  videoTracks: ArtoneTrack[];
  audioTracks: ArtoneTrack[];
  markers: ArtoneMarker[];
}

export interface ArtoneTrack {
  name: string;
  kind: 'video' | 'audio';
  clips: ArtoneClip[];
  enabled: boolean;
}

export interface ArtoneClip {
  id: string;
  name: string;
  startFrame: number;
  durationFrames: number;
  sourceInFrame: number;
  mediaUrl: string;
  effects: ArtoneEffect[];
  markers: ArtoneMarker[];
  enabled: boolean;
  /**
   * Playback speed factor (1.0 = normal, 2.0 = 2x fast, 0.5 = half speed).
   * Stored as OTIO LinearTimeWarp.1 on export; restored on import.
   * undefined and 1.0 are equivalent (normal speed, no LinearTimeWarp written).
   */
  speedFactor?: number;
  /** 前のクリップとのトランジション (in側) */
  transitionIn?: ArtoneTransition;
  /** 次のクリップとのトランジション (out側) */
  transitionOut?: ArtoneTransition;
}

export interface ArtoneTransition {
  type: 'dissolve' | 'fade' | 'wipe' | string;
  /** 入り方 (フレーム) — クリップ前のオーバーラップ */
  inFrames: number;
  /** 出方 (フレーム) — クリップ後のオーバーラップ */
  outFrames: number;
  parameters?: Record<string, unknown>;
}

export interface ArtoneEffect {
  type: string;
  name: string;
  params: Record<string, unknown>;
}

export interface ArtoneMarker {
  frame: number;
  duration: number;
  color: string;
  name: string;
  comment?: string;
}

/**
 * Describes a semantic data element that could not be fully round-tripped.
 * Generated by OTIOImporter.importWithReport() when the source OTIO file
 * contains effects or features that have no exact Artone equivalent.
 */
export interface OTIOImportLoss {
  /** Track name where the loss occurred. */
  trackName: string;
  /** Clip name where the loss occurred (empty string for track-level). */
  clipName: string;
  /** Category of the lost element. */
  field: 'effect' | 'retiming' | 'transition' | 'media_reference' | 'marker';
  /** OTIO schema or effect_name value. */
  otioType: string;
  /** Human-readable explanation. */
  detail: string;
}

/** Return type of OTIOImporter.importWithReport(). */
export interface OTIOImportResult {
  timeline: ArtoneTimeline;
  /** Elements that could not be fully restored (may be empty). */
  losses: OTIOImportLoss[];
}

// === 変換ロジック ===

const COLOR_MAP_ARTONE_TO_OTIO: Record<string, OTIOMarker['color']> = {
  red: 'RED',
  orange: 'ORANGE',
  yellow: 'YELLOW',
  green: 'GREEN',
  cyan: 'CYAN',
  blue: 'BLUE',
  purple: 'PURPLE',
  magenta: 'MAGENTA',
  pink: 'PINK',
  black: 'BLACK',
  white: 'WHITE',
};

const COLOR_MAP_OTIO_TO_ARTONE: Record<string, string> = Object.fromEntries(
  Object.entries(COLOR_MAP_ARTONE_TO_OTIO).map(([k, v]) => [v, k])
);

function rationalTime(frames: number, fps: number): OTIORationalTime {
  return { OTIO_SCHEMA: 'RationalTime.1', rate: fps, value: frames };
}

function timeRange(startFrame: number, durationFrames: number, fps: number): OTIOTimeRange {
  return {
    OTIO_SCHEMA: 'TimeRange.1',
    start_time: rationalTime(startFrame, fps),
    duration: rationalTime(durationFrames, fps),
  };
}

function fromRationalTime(rt: OTIORationalTime | null | undefined, targetFps: number): number {
  // レート差を吸収。targetFps に揃える。
  // 外部/旧/破損 OTIO に備え、欠損・非有限値は 0 に倒す (入口バリデーション)。
  if (!rt || typeof rt.value !== 'number' || !Number.isFinite(rt.value)) return 0;
  const rate = rt.rate;
  if (typeof rate !== 'number' || rate === 0 || !Number.isFinite(rate)) return 0;
  if (rate === targetFps) return Math.round(rt.value);
  // 整数演算優先で誤差軽減: (value * targetFps) / rate
  return Math.round((rt.value * targetFps) / rate);
}

// === エクスポート: Artone → OTIO ===

export class OTIOExporter {
  export(tl: ArtoneTimeline): OTIOTimeline {
    const stack: OTIOStack = {
      OTIO_SCHEMA: 'Stack.1',
      children: [
        ...tl.videoTracks.map((t) => this.toOTIOTrack(t, tl.fps)),
        ...tl.audioTracks.map((t) => this.toOTIOTrack(t, tl.fps)),
      ],
      effects: [],
      markers: tl.markers.map((m) => this.toOTIOMarker(m, tl.fps)),
      name: 'Stack',
    };

    return {
      OTIO_SCHEMA: 'Timeline.1',
      global_start_time: rationalTime(0, tl.fps),
      metadata: {
        artone: { version: '3.0.0', exported: new Date().toISOString() },
      },
      name: tl.name,
      tracks: stack,
    };
  }

  exportToString(tl: ArtoneTimeline, pretty = true): string {
    return JSON.stringify(this.export(tl), null, pretty ? 2 : 0);
  }

  private toOTIOTrack(track: ArtoneTrack, fps: number): OTIOTrack {
    // ギャップ補完: クリップ間の空白を Gap で埋める
    // トランジション: 隣接クリップ間に Transition ブロック挿入
    const sortedClips = [...track.clips].sort((a, b) => a.startFrame - b.startFrame);
    const children: OTIOTrackChild[] = [];
    let cursor = 0;

    for (let i = 0; i < sortedClips.length; i++) {
      const clip = sortedClips[i];
      if (clip.startFrame > cursor) {
        children.push(this.makeGap(clip.startFrame - cursor, fps));
      }
      children.push(this.toOTIOClip(clip, fps));
      cursor = clip.startFrame + clip.durationFrames;

      // 次クリップとのトランジション
      const next = sortedClips[i + 1];
      if (next && clip.transitionOut) {
        children.push(this.toOTIOTransition(clip.transitionOut, fps));
      }
    }

    return {
      OTIO_SCHEMA: 'Track.1',
      children,
      effects: [],
      kind: track.kind === 'video' ? 'Video' : 'Audio',
      markers: [],
      name: track.name,
      source_range: null,
    };
  }

  private toOTIOTransition(tr: ArtoneTransition, fps: number): OTIOTransition {
    const typeMap: Record<string, string> = {
      dissolve: 'SMPTE_Dissolve',
      fade: 'SMPTE_Dissolve',
      wipe: 'SMPTE_Wipe',
    };
    return {
      OTIO_SCHEMA: 'Transition.1',
      transition_type: typeMap[tr.type] ?? tr.type,
      in_offset: rationalTime(tr.inFrames, fps),
      out_offset: rationalTime(tr.outFrames, fps),
      parameters: tr.parameters,
      metadata: { artone: { type: tr.type } },
    };
  }

  private toOTIOClip(clip: ArtoneClip, fps: number): OTIOClip {
    const effects: OTIOAnyEffect[] = clip.effects.map((e) => this.toOTIOEffect(e));

    // Emit LinearTimeWarp.1 for non-normal speeds
    const speed = clip.speedFactor ?? 1.0;
    if (speed !== 1.0) {
      // OTIO convention: time_scalar > 1 means source plays slower (fewer output frames per input)
      // Artone convention: speedFactor > 1 means playback is faster (more frames per second)
      // They are reciprocal: time_scalar = 1 / speedFactor
      // REGRESSION guard: speed === 0 (freeze frame) has no finite reciprocal.
      // 1/0 = Infinity, and JSON.stringify silently turns Infinity into null,
      // producing an invalid "time_scalar": null in the exported file. Write
      // 0 instead (a valid finite JSON number) -- the exact original speed is
      // still recoverable losslessly via metadata.artone.speedFactor below,
      // which the importer reads in preference to time_scalar.
      const ltw: OTIOLinearTimeWarp = {
        OTIO_SCHEMA: 'LinearTimeWarp.1',
        effect_name: 'LinearTimeWarp',
        time_scalar: speed !== 0 ? 1 / speed : 0,
        metadata: { artone: { speedFactor: speed } },
      };
      effects.push(ltw);
    }

    return {
      OTIO_SCHEMA: 'Clip.2',
      effects,
      markers: clip.markers.map((m) => this.toOTIOMarker(m, fps)),
      media_reference: {
        OTIO_SCHEMA: 'ExternalReference.1',
        target_url: clip.mediaUrl,
        name: clip.name,
      },
      metadata: { artone: { clipId: clip.id } },
      name: clip.name,
      source_range: timeRange(clip.sourceInFrame, clip.durationFrames, fps),
      enabled: clip.enabled,
    };
  }

  private makeGap(durationFrames: number, fps: number): OTIOGap {
    return {
      OTIO_SCHEMA: 'Gap.1',
      effects: [],
      markers: [],
      source_range: timeRange(0, durationFrames, fps),
    };
  }

  private toOTIOEffect(eff: ArtoneEffect): OTIOEffect {
    return {
      OTIO_SCHEMA: 'Effect.1',
      effect_name: eff.type,
      name: eff.name,
      metadata: { artone: { params: eff.params } },
    };
  }

  private toOTIOMarker(m: ArtoneMarker, fps: number): OTIOMarker {
    return {
      OTIO_SCHEMA: 'Marker.2',
      color: COLOR_MAP_ARTONE_TO_OTIO[m.color.toLowerCase()] ?? 'RED',
      marked_range: timeRange(m.frame, m.duration, fps),
      name: m.name,
      comment: m.comment,
    };
  }
}

// === インポート: OTIO → Artone ===

export class OTIOImporter {
  /**
   * Validate and return the timeline's Stack. External/old/corrupt OTIO must
   * fail with a clear message at the entry point rather than a cryptic
   * "Cannot read properties of undefined" deep in the conversion.
   */
  /**
   * Recovers Artone's speedFactor from an imported LinearTimeWarp.1 effect.
   * Prefers the exact value round-tripped in metadata.artone.speedFactor
   * (written by OTIOExporter.toOTIOClip) over 1/time_scalar, since speed=0
   * (freeze frame) has no finite reciprocal and time_scalar alone cannot
   * represent it losslessly.
   */
  private speedFactorFromLinearTimeWarp(ltw: OTIOLinearTimeWarp): number {
    const fromMeta = (ltw.metadata?.artone as { speedFactor?: unknown } | undefined)?.speedFactor;
    if (typeof fromMeta === 'number' && Number.isFinite(fromMeta)) return fromMeta;
    return ltw.time_scalar !== 0 ? 1 / ltw.time_scalar : 1;
  }

  private requireStack(tl: OTIOTimeline): OTIOStack {
    const stack = tl?.tracks;
    if (!stack || stack.OTIO_SCHEMA !== 'Stack.1' || !Array.isArray(stack.children)) {
      throw new Error('Invalid OTIO: timeline.tracks must be a Stack.1 with a children array');
    }
    return stack;
  }

  /**
   * Import and return both the timeline and a list of elements that could not
   * be fully round-tripped (e.g. foreign tool effects, unsupported retiming).
   */
  importWithReport(json: string, targetFps?: number): OTIOImportResult {
    let parsed: OTIOTimeline;
    try {
      parsed = JSON.parse(json) as OTIOTimeline;
    } catch (err) {
      throw new Error(`Invalid OTIO JSON: ${(err as Error).message}`);
    }
    if (parsed?.OTIO_SCHEMA !== 'Timeline.1') {
      throw new Error(`Unsupported OTIO schema: ${parsed?.OTIO_SCHEMA}`);
    }
    const stack = this.requireStack(parsed);
    const losses: OTIOImportLoss[] = [];
    // Guard against rate=0 or NaN in global_start_time: fromRationalTime would
    // compute Math.round(value * 0 / rate) = 0 for every frame, silently
    // zeroing all clip positions and durations.
    const rawFps = targetFps ?? parsed.global_start_time?.rate;
    const fps = (typeof rawFps === 'number' && Number.isFinite(rawFps) && rawFps > 0) ? rawFps : 30;

    const videoTracks: ArtoneTrack[] = [];
    const audioTracks: ArtoneTrack[] = [];

    for (const track of stack.children) {
      const { artoneTrack, trackLosses } = this.fromOTIOTrackWithReport(track, fps);
      if (track.kind === 'Video') videoTracks.push(artoneTrack);
      else audioTracks.push(artoneTrack);
      losses.push(...trackLosses);
    }

    return {
      timeline: {
        name: parsed.name,
        fps,
        videoTracks,
        audioTracks,
        markers: (stack.markers ?? []).map((m) => this.fromOTIOMarker(m, fps)),
      },
      losses,
    };
  }

  import(otio: OTIOTimeline, targetFps?: number): ArtoneTimeline {
    const stack = this.requireStack(otio);
    const rawFps = targetFps ?? otio.global_start_time?.rate;
    const fps = (typeof rawFps === 'number' && Number.isFinite(rawFps) && rawFps > 0) ? rawFps : 30;

    const videoTracks: ArtoneTrack[] = [];
    const audioTracks: ArtoneTrack[] = [];

    for (const track of stack.children) {
      const artoneTrack = this.fromOTIOTrack(track, fps);
      if (track.kind === 'Video') videoTracks.push(artoneTrack);
      else audioTracks.push(artoneTrack);
    }

    return {
      name: otio.name,
      fps,
      videoTracks,
      audioTracks,
      markers: (stack.markers ?? []).map((m) => this.fromOTIOMarker(m, fps)),
    };
  }

  importFromString(json: string, targetFps?: number): ArtoneTimeline {
    let otio: OTIOTimeline;
    try {
      otio = JSON.parse(json) as OTIOTimeline;
    } catch (err) {
      throw new Error(`Invalid OTIO JSON: ${(err as Error).message}`);
    }
    if (otio.OTIO_SCHEMA !== 'Timeline.1') {
      throw new Error(`Unsupported OTIO schema: ${otio.OTIO_SCHEMA}`);
    }
    return this.import(otio, targetFps);
  }

  private fromOTIOTrackWithReport(
    track: OTIOTrack,
    fps: number,
  ): { artoneTrack: ArtoneTrack; trackLosses: OTIOImportLoss[] } {
    const losses: OTIOImportLoss[] = [];
    const clips: ArtoneClip[] = [];
    let cursor = 0;
    let pendingTransition: ArtoneTransition | null = null;
    const trackName = track.name ?? 'Track';

    // REGRESSION fix: track.markers (Track is itself a Composition/Item and
    // can carry its own markers per the OTIO spec -- distinct from markers
    // on the top-level Stack or on individual Clips) was never read here.
    // ArtoneTrack has no field to hold them, so unlike Stack/Clip markers
    // they cannot be represented after import -- report the loss instead of
    // silently dropping them, matching the effect/transition/media_reference
    // loss-report contract.
    for (const marker of track.markers ?? []) {
      losses.push({
        trackName,
        clipName: '',
        field: 'marker',
        otioType: marker.OTIO_SCHEMA,
        detail: `Track-level marker "${marker.name ?? ''}" has no Artone equivalent (Artone only supports timeline- and clip-level markers) and was dropped.`,
      });
    }

    for (const child of track.children ?? []) {
      if (child.OTIO_SCHEMA === 'Clip.1' || child.OTIO_SCHEMA === 'Clip.2') {
        const { clip: artoneClip, clipLosses } = this.fromOTIOClipWithReport(
          child as OTIOClip, cursor, fps, trackName,
        );
        if (pendingTransition) {
          // Use separate copies so mutating transitionIn on one clip does not
          // accidentally alter transitionOut on the other (aliasing bug).
          artoneClip.transitionIn = { ...pendingTransition };
          const prev = clips[clips.length - 1];
          if (prev) prev.transitionOut = { ...pendingTransition };
          pendingTransition = null;
        }
        clips.push(artoneClip);
        cursor += fromRationalTime((child as OTIOClip).source_range?.duration, fps);
        losses.push(...clipLosses);
      } else if (child.OTIO_SCHEMA === 'Gap.1') {
        cursor += fromRationalTime((child as OTIOGap).source_range?.duration, fps);
      } else if (child.OTIO_SCHEMA === 'Transition.1') {
        const tr = child as OTIOTransition;
        const inFrames = fromRationalTime(tr.in_offset, fps);
        const outFrames = fromRationalTime(tr.out_offset, fps);
        const meta = (tr.metadata?.artone as { type?: string } | undefined)?.type;
        const type = meta ?? (tr.transition_type === 'SMPTE_Dissolve' ? 'dissolve' : tr.transition_type);
        if (!meta && tr.transition_type !== 'SMPTE_Dissolve' && tr.transition_type !== 'SMPTE_Wipe') {
          losses.push({
            trackName,
            clipName: '',
            field: 'transition',
            otioType: tr.transition_type,
            detail: `Transition type "${tr.transition_type}" has no Artone equivalent; stored as custom type.`,
          });
        }
        pendingTransition = { type, inFrames, outFrames, parameters: tr.parameters };
      }
    }

    return {
      artoneTrack: { name: trackName, kind: track.kind === 'Video' ? 'video' : 'audio', clips, enabled: true },
      trackLosses: losses,
    };
  }

  private fromOTIOClipWithReport(
    clip: OTIOClip,
    startFrame: number,
    fps: number,
    trackName: string,
  ): { clip: ArtoneClip; clipLosses: OTIOImportLoss[] } {
    const losses: OTIOImportLoss[] = [];
    const ref = clip.media_reference;
    const url = ref?.OTIO_SCHEMA === 'ExternalReference.1' ? ref.target_url ?? '' : '';
    const artoneId =
      (clip.metadata?.artone as { clipId?: string } | undefined)?.clipId ??
      `imported-${Math.random().toString(36).slice(2, 11)}`;

    if (ref?.OTIO_SCHEMA === 'MissingReference.1') {
      losses.push({
        trackName,
        clipName: clip.name,
        field: 'media_reference',
        otioType: 'MissingReference.1',
        detail: 'Media file could not be resolved; clip will have empty mediaUrl.',
      });
    } else if (ref?.OTIO_SCHEMA === 'GeneratorReference.1') {
      // REGRESSION fix: this fell through the same `url = ''` default as
      // MissingReference.1 above (Artone has no generated-media concept —
      // color bars/slugs/solids), but unlike that case produced no loss
      // entry, silently swallowing the same practical outcome (empty
      // mediaUrl) that the sibling branch explicitly reports.
      losses.push({
        trackName,
        clipName: clip.name,
        field: 'media_reference',
        otioType: 'GeneratorReference.1',
        detail: 'Generated media (color bars/slug/solid) is not supported; clip will have empty mediaUrl.',
      });
    }

    let speedFactor: number | undefined;
    const artoneEffects: ArtoneEffect[] = [];

    for (const eff of clip.effects ?? []) {
      if (eff.OTIO_SCHEMA === 'LinearTimeWarp.1') {
        const ltw = eff as OTIOLinearTimeWarp;
        speedFactor = this.speedFactorFromLinearTimeWarp(ltw);
      } else {
        const artoneEff = this.fromOTIOEffect(eff as OTIOEffect);
        artoneEffects.push(artoneEff);
        // Report foreign effects (no artone metadata means they came from another NLE)
        const hasMeta = !!(eff.metadata?.artone as Record<string, unknown> | undefined)?.params;
        if (!hasMeta) {
          losses.push({
            trackName,
            clipName: clip.name,
            field: 'effect',
            otioType: `${eff.OTIO_SCHEMA}:${(eff as OTIOEffect).effect_name}`,
            detail: `Effect "${(eff as OTIOEffect).effect_name}" came from another tool and may not render correctly.`,
          });
        }
      }
    }

    return {
      clip: {
        id: artoneId,
        name: clip.name,
        startFrame,
        durationFrames: fromRationalTime(clip.source_range?.duration, fps),
        sourceInFrame: fromRationalTime(clip.source_range?.start_time, fps),
        mediaUrl: url,
        effects: artoneEffects,
        markers: (clip.markers ?? []).map((m) => this.fromOTIOMarker(m, fps)),
        enabled: clip.enabled ?? true,
        ...(speedFactor !== undefined ? { speedFactor } : {}),
      },
      clipLosses: losses,
    };
  }

  private fromOTIOTrack(track: OTIOTrack, fps: number): ArtoneTrack {
    const clips: ArtoneClip[] = [];
    let cursor = 0;
    let pendingTransition: ArtoneTransition | null = null;

    for (const child of track.children ?? []) {
      if (child.OTIO_SCHEMA === 'Clip.1' || child.OTIO_SCHEMA === 'Clip.2') {
        const artoneClip = this.fromOTIOClip(child as OTIOClip, cursor, fps);
        if (pendingTransition) {
          // Use separate copies — same aliasing guard as fromOTIOTrackWithReport.
          artoneClip.transitionIn = { ...pendingTransition };
          // 直前クリップに transitionOut も付与
          const prev = clips[clips.length - 1];
          if (prev) prev.transitionOut = { ...pendingTransition };
          pendingTransition = null;
        }
        clips.push(artoneClip);
        cursor += fromRationalTime((child as OTIOClip).source_range?.duration, fps);
      } else if (child.OTIO_SCHEMA === 'Gap.1') {
        cursor += fromRationalTime((child as OTIOGap).source_range?.duration, fps);
      } else if (child.OTIO_SCHEMA === 'Transition.1') {
        const tr = child as OTIOTransition;
        const inFrames = fromRationalTime(tr.in_offset, fps);
        const outFrames = fromRationalTime(tr.out_offset, fps);
        const meta = (tr.metadata?.artone as { type?: string } | undefined)?.type;
        pendingTransition = {
          type: meta ?? (tr.transition_type === 'SMPTE_Dissolve' ? 'dissolve' : tr.transition_type),
          inFrames,
          outFrames,
          parameters: tr.parameters,
        };
      }
    }

    return {
      name: track.name ?? 'Track',
      kind: track.kind === 'Video' ? 'video' : 'audio',
      clips,
      enabled: true,
    };
  }

  private fromOTIOClip(clip: OTIOClip, startFrame: number, fps: number): ArtoneClip {
    const ref = clip.media_reference;
    const url = ref?.OTIO_SCHEMA === 'ExternalReference.1' ? ref.target_url ?? '' : '';
    const artoneId =
      (clip.metadata?.artone as { clipId?: string } | undefined)?.clipId ??
      `imported-${Math.random().toString(36).slice(2, 11)}`;

    let speedFactor: number | undefined;
    const effects: ArtoneEffect[] = [];
    for (const eff of clip.effects ?? []) {
      if (eff.OTIO_SCHEMA === 'LinearTimeWarp.1') {
        const ltw = eff as OTIOLinearTimeWarp;
        speedFactor = this.speedFactorFromLinearTimeWarp(ltw);
      } else {
        effects.push(this.fromOTIOEffect(eff as OTIOEffect));
      }
    }

    return {
      id: artoneId,
      name: clip.name,
      startFrame,
      durationFrames: fromRationalTime(clip.source_range?.duration, fps),
      sourceInFrame: fromRationalTime(clip.source_range?.start_time, fps),
      mediaUrl: url,
      effects,
      markers: (clip.markers ?? []).map((m) => this.fromOTIOMarker(m, fps)),
      enabled: clip.enabled ?? true,
      ...(speedFactor !== undefined ? { speedFactor } : {}),
    };
  }

  private fromOTIOEffect(eff: OTIOEffect): ArtoneEffect {
    const params =
      (eff.metadata?.artone as { params?: Record<string, unknown> } | undefined)?.params ?? {};
    return { type: eff.effect_name, name: eff.name ?? eff.effect_name, params };
  }

  private fromOTIOMarker(m: OTIOMarker, fps: number): ArtoneMarker {
    return {
      frame: fromRationalTime(m.marked_range?.start_time, fps),
      duration: fromRationalTime(m.marked_range?.duration, fps),
      color: COLOR_MAP_OTIO_TO_ARTONE[m.color] ?? 'red',
      name: m.name ?? '',
      comment: m.comment,
    };
  }
}

// === 検証 ===

export class OTIOValidator {
  validate(otio: unknown): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const t = otio as Partial<OTIOTimeline>;

    if (t.OTIO_SCHEMA !== 'Timeline.1') errors.push('Root schema must be Timeline.1');
    if (!t.tracks) errors.push('Missing tracks (Stack)');
    else if (t.tracks.OTIO_SCHEMA !== 'Stack.1') errors.push('tracks must be Stack.1');
    if (typeof t.name !== 'string') errors.push('Missing name');

    return { valid: errors.length === 0, errors };
  }
}

// === ファクトリ ===

export const otio = {
  exporter: () => new OTIOExporter(),
  importer: () => new OTIOImporter(),
  validator: () => new OTIOValidator(),
};

